### ISSUE TITLE
预训练权重报错

### ISSUE THREAD

**Issue by LJWERIC1121** [Hector0426/fine-grained-image-classification-with-vit#3]
您好，我们通过您提供的预权重训练，出现以下问题：
Traceback (most recent call last):
  File "E:\paper_code\file\ACC-ViT-PR\main.py", line 47, in <module>
    model.load_from(np.load(vit_pretrain))
  File "E:\paper_code\file\ACC-ViT-PR\model.py", line 373, in load_from
    unit.load_from(weights, n_block=uname)
  File "E:\paper_code\file\ACC-ViT-PR\model.py", line 161, in load_from
    query_weight = np2th(weights[pjoin(ROOT, ATTENTION_Q, "kernel")]).view(self.hidden_size,
  File "C:\Users\Ljw\.conda\envs\pytorch\lib\site-packages\numpy\lib\npyio.py", line 260, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'Transformer/encoderblock_0\\MultiHeadDotProductAttention_1/query\\kernel is not a file in the archive'
如果您有时间能否帮我们解答一下

**Comment by SX-SS** [comment]
https://blog.csdn.net/qq_37278761/article/details/121493618
This blog might help you.
